# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ploteditorgui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PlotEditor(object):
    def setupUi(self, PlotEditor):
        PlotEditor.setObjectName("PlotEditor")
        PlotEditor.resize(1071, 903)
        PlotEditor.setMinimumSize(QtCore.QSize(710, 499))
        PlotEditor.setFocusPolicy(QtCore.Qt.NoFocus)
        PlotEditor.setToolTipDuration(-5)
        self.layoutWidget = QtWidgets.QWidget(PlotEditor)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 100, 368, 241))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.vertical_label_le = QtWidgets.QLineEdit(self.layoutWidget)
        self.vertical_label_le.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.vertical_label_le.setFont(font)
        self.vertical_label_le.setText("")
        self.vertical_label_le.setObjectName("vertical_label_le")
        self.gridLayout.addWidget(self.vertical_label_le, 2, 0, 1, 4)
        self.font_size_sb = QtWidgets.QComboBox(self.layoutWidget)
        self.font_size_sb.setEnabled(True)
        self.font_size_sb.setMinimumSize(QtCore.QSize(0, 0))
        self.font_size_sb.setMaximumSize(QtCore.QSize(100, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.font_size_sb.setFont(font)
        self.font_size_sb.setEditable(True)
        self.font_size_sb.setMaxVisibleItems(16)
        self.font_size_sb.setMinimumContentsLength(0)
        self.font_size_sb.setObjectName("font_size_sb")
        self.font_size_sb.addItem("")
        self.font_size_sb.addItem("")
        self.font_size_sb.addItem("")
        self.font_size_sb.addItem("")
        self.font_size_sb.addItem("")
        self.font_size_sb.addItem("")
        self.font_size_sb.addItem("")
        self.font_size_sb.addItem("")
        self.font_size_sb.addItem("")
        self.font_size_sb.addItem("")
        self.font_size_sb.addItem("")
        self.font_size_sb.addItem("")
        self.font_size_sb.addItem("")
        self.gridLayout.addWidget(self.font_size_sb, 4, 3, 1, 1)
        self.fat_pb = QtWidgets.QPushButton(self.layoutWidget)
        self.fat_pb.setMaximumSize(QtCore.QSize(50, 46))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.fat_pb.setFont(font)
        self.fat_pb.setObjectName("fat_pb")
        self.gridLayout.addWidget(self.fat_pb, 4, 2, 1, 1)
        self.horizontal_label_le = QtWidgets.QLineEdit(self.layoutWidget)
        self.horizontal_label_le.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.horizontal_label_le.setFont(font)
        self.horizontal_label_le.setInputMask("")
        self.horizontal_label_le.setText("")
        self.horizontal_label_le.setFrame(True)
        self.horizontal_label_le.setObjectName("horizontal_label_le")
        self.gridLayout.addWidget(self.horizontal_label_le, 1, 0, 1, 4)
        self.axes_label_color_cb = QtWidgets.QComboBox(self.layoutWidget)
        self.axes_label_color_cb.setMaximumSize(QtCore.QSize(114, 31))
        self.axes_label_color_cb.setObjectName("axes_label_color_cb")
        self.axes_label_color_cb.addItem("")
        self.axes_label_color_cb.addItem("")
        self.axes_label_color_cb.addItem("")
        self.axes_label_color_cb.addItem("")
        self.axes_label_color_cb.addItem("")
        self.axes_label_color_cb.addItem("")
        self.axes_label_color_cb.addItem("")
        self.gridLayout.addWidget(self.axes_label_color_cb, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 2)
        self.font_sb = QtWidgets.QFontComboBox(self.layoutWidget)
        self.font_sb.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.font_sb.setFont(font)
        self.font_sb.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.font_sb.setEditable(False)
        self.font_sb.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.font_sb.setFontFilters(QtWidgets.QFontComboBox.AllFonts)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.font_sb.setCurrentFont(font)
        self.font_sb.setObjectName("font_sb")
        self.gridLayout.addWidget(self.font_sb, 3, 0, 1, 4)
        self.kursive_pb = QtWidgets.QPushButton(self.layoutWidget)
        self.kursive_pb.setMaximumSize(QtCore.QSize(50, 46))
        font = QtGui.QFont()
        font.setItalic(True)
        self.kursive_pb.setFont(font)
        self.kursive_pb.setObjectName("kursive_pb")
        self.gridLayout.addWidget(self.kursive_pb, 4, 1, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(PlotEditor)
        self.layoutWidget1.setGeometry(QtCore.QRect(420, 100, 611, 281))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_le = QtWidgets.QLineEdit(self.layoutWidget1)
        self.label_le.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_le.setFont(font)
        self.label_le.setInputMask("")
        self.label_le.setText("")
        self.label_le.setFrame(True)
        self.label_le.setObjectName("label_le")
        self.gridLayout_3.addWidget(self.label_le, 1, 0, 1, 4)
        self.legend_color_cb = QtWidgets.QComboBox(self.layoutWidget1)
        self.legend_color_cb.setMaximumSize(QtCore.QSize(114, 31))
        self.legend_color_cb.setObjectName("legend_color_cb")
        self.legend_color_cb.addItem("")
        self.legend_color_cb.addItem("")
        self.legend_color_cb.addItem("")
        self.legend_color_cb.addItem("")
        self.legend_color_cb.addItem("")
        self.legend_color_cb.addItem("")
        self.legend_color_cb.addItem("")
        self.gridLayout_3.addWidget(self.legend_color_cb, 3, 0, 1, 1)
        self.label_l = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_l.setFont(font)
        self.label_l.setObjectName("label_l")
        self.gridLayout_3.addWidget(self.label_l, 0, 0, 1, 4)
        self.legend_font_size_sb = QtWidgets.QComboBox(self.layoutWidget1)
        self.legend_font_size_sb.setEnabled(True)
        self.legend_font_size_sb.setMinimumSize(QtCore.QSize(0, 0))
        self.legend_font_size_sb.setMaximumSize(QtCore.QSize(100, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.legend_font_size_sb.setFont(font)
        self.legend_font_size_sb.setEditable(True)
        self.legend_font_size_sb.setMaxVisibleItems(16)
        self.legend_font_size_sb.setMinimumContentsLength(0)
        self.legend_font_size_sb.setObjectName("legend_font_size_sb")
        self.legend_font_size_sb.addItem("")
        self.legend_font_size_sb.addItem("")
        self.legend_font_size_sb.addItem("")
        self.legend_font_size_sb.addItem("")
        self.legend_font_size_sb.addItem("")
        self.legend_font_size_sb.addItem("")
        self.legend_font_size_sb.addItem("")
        self.legend_font_size_sb.addItem("")
        self.legend_font_size_sb.addItem("")
        self.legend_font_size_sb.addItem("")
        self.legend_font_size_sb.addItem("")
        self.legend_font_size_sb.addItem("")
        self.legend_font_size_sb.addItem("")
        self.gridLayout_3.addWidget(self.legend_font_size_sb, 3, 3, 1, 1)
        self.legend_fat_pb = QtWidgets.QPushButton(self.layoutWidget1)
        self.legend_fat_pb.setMaximumSize(QtCore.QSize(50, 46))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.legend_fat_pb.setFont(font)
        self.legend_fat_pb.setObjectName("legend_fat_pb")
        self.gridLayout_3.addWidget(self.legend_fat_pb, 3, 1, 1, 1)
        self.legend_pos_cb = QtWidgets.QComboBox(self.layoutWidget1)
        self.legend_pos_cb.setObjectName("legend_pos_cb")
        self.legend_pos_cb.addItem("")
        self.legend_pos_cb.addItem("")
        self.legend_pos_cb.addItem("")
        self.legend_pos_cb.addItem("")
        self.legend_pos_cb.addItem("")
        self.legend_pos_cb.addItem("")
        self.legend_pos_cb.addItem("")
        self.legend_pos_cb.addItem("")
        self.legend_pos_cb.addItem("")
        self.legend_pos_cb.addItem("")
        self.legend_pos_cb.addItem("")
        self.gridLayout_3.addWidget(self.legend_pos_cb, 4, 1, 1, 1)
        self.legend_pos_lb = QtWidgets.QLabel(self.layoutWidget1)
        self.legend_pos_lb.setObjectName("legend_pos_lb")
        self.gridLayout_3.addWidget(self.legend_pos_lb, 4, 0, 1, 1)
        self.legend_facecolor_lb = QtWidgets.QLabel(self.layoutWidget1)
        self.legend_facecolor_lb.setObjectName("legend_facecolor_lb")
        self.gridLayout_3.addWidget(self.legend_facecolor_lb, 5, 0, 1, 1)
        self.legend_facecolor_cb = QtWidgets.QComboBox(self.layoutWidget1)
        self.legend_facecolor_cb.setMaximumSize(QtCore.QSize(114, 31))
        self.legend_facecolor_cb.setObjectName("legend_facecolor_cb")
        self.legend_facecolor_cb.addItem("")
        self.legend_facecolor_cb.addItem("")
        self.legend_facecolor_cb.addItem("")
        self.legend_facecolor_cb.addItem("")
        self.legend_facecolor_cb.addItem("")
        self.legend_facecolor_cb.addItem("")
        self.legend_facecolor_cb.addItem("")
        self.gridLayout_3.addWidget(self.legend_facecolor_cb, 5, 1, 1, 1)
        self.legend_kursive_pb = QtWidgets.QPushButton(self.layoutWidget1)
        self.legend_kursive_pb.setMaximumSize(QtCore.QSize(50, 46))
        font = QtGui.QFont()
        font.setItalic(True)
        self.legend_kursive_pb.setFont(font)
        self.legend_kursive_pb.setObjectName("legend_kursive_pb")
        self.gridLayout_3.addWidget(self.legend_kursive_pb, 3, 2, 1, 1)
        self.legend_font_sb = QtWidgets.QFontComboBox(self.layoutWidget1)
        self.legend_font_sb.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.legend_font_sb.setFont(font)
        self.legend_font_sb.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.legend_font_sb.setEditable(False)
        self.legend_font_sb.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.legend_font_sb.setFontFilters(QtWidgets.QFontComboBox.AllFonts)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.legend_font_sb.setCurrentFont(font)
        self.legend_font_sb.setObjectName("legend_font_sb")
        self.gridLayout_3.addWidget(self.legend_font_sb, 2, 0, 1, 4)
        self.layoutWidget2 = QtWidgets.QWidget(PlotEditor)
        self.layoutWidget2.setGeometry(QtCore.QRect(50, 480, 351, 91))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.linestyle_cb = QtWidgets.QComboBox(self.layoutWidget2)
        self.linestyle_cb.setObjectName("linestyle_cb")
        self.linestyle_cb.addItem("")
        self.linestyle_cb.addItem("")
        self.linestyle_cb.addItem("")
        self.gridLayout_2.addWidget(self.linestyle_cb, 2, 2, 1, 1)
        self.line_color_cb = QtWidgets.QComboBox(self.layoutWidget2)
        self.line_color_cb.setMaximumSize(QtCore.QSize(114, 31))
        self.line_color_cb.setObjectName("line_color_cb")
        self.line_color_cb.addItem("")
        self.line_color_cb.addItem("")
        self.line_color_cb.addItem("")
        self.line_color_cb.addItem("")
        self.line_color_cb.addItem("")
        self.line_color_cb.addItem("")
        self.line_color_cb.addItem("")
        self.gridLayout_2.addWidget(self.line_color_cb, 2, 0, 1, 1)
        self.linewidth_cb = QtWidgets.QComboBox(self.layoutWidget2)
        self.linewidth_cb.setEnabled(True)
        self.linewidth_cb.setMaximumSize(QtCore.QSize(66, 31))
        self.linewidth_cb.setInputMethodHints(QtCore.Qt.ImhNone)
        self.linewidth_cb.setEditable(True)
        self.linewidth_cb.setObjectName("linewidth_cb")
        self.linewidth_cb.addItem("")
        self.linewidth_cb.addItem("")
        self.linewidth_cb.addItem("")
        self.linewidth_cb.addItem("")
        self.linewidth_cb.addItem("")
        self.linewidth_cb.addItem("")
        self.linewidth_cb.addItem("")
        self.linewidth_cb.addItem("")
        self.linewidth_cb.addItem("")
        self.linewidth_cb.addItem("")
        self.linewidth_cb.addItem("")
        self.gridLayout_2.addWidget(self.linewidth_cb, 2, 1, 1, 1)
        self.linestyle_l = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.linestyle_l.setFont(font)
        self.linestyle_l.setObjectName("linestyle_l")
        self.gridLayout_2.addWidget(self.linestyle_l, 0, 0, 1, 2)
        self.layoutWidget3 = QtWidgets.QWidget(PlotEditor)
        self.layoutWidget3.setGeometry(QtCore.QRect(420, 480, 321, 131))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.figure_size_slider = QtWidgets.QSlider(self.layoutWidget3)
        self.figure_size_slider.setMinimum(1)
        self.figure_size_slider.setMaximum(1000)
        self.figure_size_slider.setSliderPosition(500)
        self.figure_size_slider.setOrientation(QtCore.Qt.Horizontal)
        self.figure_size_slider.setObjectName("figure_size_slider")
        self.gridLayout_4.addWidget(self.figure_size_slider, 2, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.layoutWidget3)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)
        self.background_color_cb = QtWidgets.QComboBox(self.layoutWidget3)
        self.background_color_cb.setMaximumSize(QtCore.QSize(114, 31))
        self.background_color_cb.setObjectName("background_color_cb")
        self.background_color_cb.addItem("")
        self.background_color_cb.addItem("")
        self.background_color_cb.addItem("")
        self.background_color_cb.addItem("")
        self.background_color_cb.addItem("")
        self.background_color_cb.addItem("")
        self.background_color_cb.addItem("")
        self.gridLayout_4.addWidget(self.background_color_cb, 1, 1, 1, 1)
        self.show_plot_bt = QtWidgets.QPushButton(PlotEditor)
        self.show_plot_bt.setGeometry(QtCore.QRect(340, 790, 312, 47))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.show_plot_bt.setFont(font)
        self.show_plot_bt.setObjectName("show_plot_bt")

        self.retranslateUi(PlotEditor)
        self.legend_facecolor_cb.setCurrentIndex(1)
        self.linewidth_cb.setCurrentIndex(3)
        self.background_color_cb.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(PlotEditor)

    def retranslateUi(self, PlotEditor):
        _translate = QtCore.QCoreApplication.translate
        PlotEditor.setWindowTitle(_translate("PlotEditor", "Plot Editor"))
        self.vertical_label_le.setPlaceholderText(_translate("PlotEditor", "y"))
        self.font_size_sb.setItemText(0, _translate("PlotEditor", "8"))
        self.font_size_sb.setItemText(1, _translate("PlotEditor", "9"))
        self.font_size_sb.setItemText(2, _translate("PlotEditor", "10"))
        self.font_size_sb.setItemText(3, _translate("PlotEditor", "11"))
        self.font_size_sb.setItemText(4, _translate("PlotEditor", "12"))
        self.font_size_sb.setItemText(5, _translate("PlotEditor", "14"))
        self.font_size_sb.setItemText(6, _translate("PlotEditor", "16"))
        self.font_size_sb.setItemText(7, _translate("PlotEditor", "18"))
        self.font_size_sb.setItemText(8, _translate("PlotEditor", "20"))
        self.font_size_sb.setItemText(9, _translate("PlotEditor", "22"))
        self.font_size_sb.setItemText(10, _translate("PlotEditor", "24"))
        self.font_size_sb.setItemText(11, _translate("PlotEditor", "26"))
        self.font_size_sb.setItemText(12, _translate("PlotEditor", "28"))
        self.fat_pb.setText(_translate("PlotEditor", "F"))
        self.horizontal_label_le.setPlaceholderText(_translate("PlotEditor", "x"))
        self.axes_label_color_cb.setItemText(0, _translate("PlotEditor", "black"))
        self.axes_label_color_cb.setItemText(1, _translate("PlotEditor", "white"))
        self.axes_label_color_cb.setItemText(2, _translate("PlotEditor", "red"))
        self.axes_label_color_cb.setItemText(3, _translate("PlotEditor", "blue"))
        self.axes_label_color_cb.setItemText(4, _translate("PlotEditor", "green"))
        self.axes_label_color_cb.setItemText(5, _translate("PlotEditor", "yellow"))
        self.axes_label_color_cb.setItemText(6, _translate("PlotEditor", "purple"))
        self.label_2.setText(_translate("PlotEditor", "Axes"))
        self.kursive_pb.setText(_translate("PlotEditor", "K"))
        self.label_le.setPlaceholderText(_translate("PlotEditor", "legend"))
        self.legend_color_cb.setItemText(0, _translate("PlotEditor", "black"))
        self.legend_color_cb.setItemText(1, _translate("PlotEditor", "white"))
        self.legend_color_cb.setItemText(2, _translate("PlotEditor", "red"))
        self.legend_color_cb.setItemText(3, _translate("PlotEditor", "blue"))
        self.legend_color_cb.setItemText(4, _translate("PlotEditor", "green"))
        self.legend_color_cb.setItemText(5, _translate("PlotEditor", "yellow"))
        self.legend_color_cb.setItemText(6, _translate("PlotEditor", "purple"))
        self.label_l.setText(_translate("PlotEditor", "Legend"))
        self.legend_font_size_sb.setItemText(0, _translate("PlotEditor", "8"))
        self.legend_font_size_sb.setItemText(1, _translate("PlotEditor", "9"))
        self.legend_font_size_sb.setItemText(2, _translate("PlotEditor", "10"))
        self.legend_font_size_sb.setItemText(3, _translate("PlotEditor", "11"))
        self.legend_font_size_sb.setItemText(4, _translate("PlotEditor", "12"))
        self.legend_font_size_sb.setItemText(5, _translate("PlotEditor", "14"))
        self.legend_font_size_sb.setItemText(6, _translate("PlotEditor", "16"))
        self.legend_font_size_sb.setItemText(7, _translate("PlotEditor", "18"))
        self.legend_font_size_sb.setItemText(8, _translate("PlotEditor", "20"))
        self.legend_font_size_sb.setItemText(9, _translate("PlotEditor", "22"))
        self.legend_font_size_sb.setItemText(10, _translate("PlotEditor", "24"))
        self.legend_font_size_sb.setItemText(11, _translate("PlotEditor", "26"))
        self.legend_font_size_sb.setItemText(12, _translate("PlotEditor", "28"))
        self.legend_fat_pb.setText(_translate("PlotEditor", "F"))
        self.legend_pos_cb.setItemText(0, _translate("PlotEditor", "automatic"))
        self.legend_pos_cb.setItemText(1, _translate("PlotEditor", "upper right"))
        self.legend_pos_cb.setItemText(2, _translate("PlotEditor", "upper left"))
        self.legend_pos_cb.setItemText(3, _translate("PlotEditor", "lower left"))
        self.legend_pos_cb.setItemText(4, _translate("PlotEditor", "lower right"))
        self.legend_pos_cb.setItemText(5, _translate("PlotEditor", "right"))
        self.legend_pos_cb.setItemText(6, _translate("PlotEditor", "center left"))
        self.legend_pos_cb.setItemText(7, _translate("PlotEditor", "center right"))
        self.legend_pos_cb.setItemText(8, _translate("PlotEditor", "lower center"))
        self.legend_pos_cb.setItemText(9, _translate("PlotEditor", "upper center"))
        self.legend_pos_cb.setItemText(10, _translate("PlotEditor", "center"))
        self.legend_pos_lb.setText(_translate("PlotEditor", "Position:"))
        self.legend_facecolor_lb.setText(_translate("PlotEditor", "Background Color:"))
        self.legend_facecolor_cb.setItemText(0, _translate("PlotEditor", "black"))
        self.legend_facecolor_cb.setItemText(1, _translate("PlotEditor", "white"))
        self.legend_facecolor_cb.setItemText(2, _translate("PlotEditor", "red"))
        self.legend_facecolor_cb.setItemText(3, _translate("PlotEditor", "blue"))
        self.legend_facecolor_cb.setItemText(4, _translate("PlotEditor", "green"))
        self.legend_facecolor_cb.setItemText(5, _translate("PlotEditor", "yellow"))
        self.legend_facecolor_cb.setItemText(6, _translate("PlotEditor", "purple"))
        self.legend_kursive_pb.setText(_translate("PlotEditor", "K"))
        self.linestyle_cb.setItemText(0, _translate("PlotEditor", "________"))
        self.linestyle_cb.setItemText(1, _translate("PlotEditor", "_ _ _ _ _"))
        self.linestyle_cb.setItemText(2, _translate("PlotEditor", ". . . . . . . "))
        self.line_color_cb.setItemText(0, _translate("PlotEditor", "black"))
        self.line_color_cb.setItemText(1, _translate("PlotEditor", "white"))
        self.line_color_cb.setItemText(2, _translate("PlotEditor", "red"))
        self.line_color_cb.setItemText(3, _translate("PlotEditor", "blue"))
        self.line_color_cb.setItemText(4, _translate("PlotEditor", "green"))
        self.line_color_cb.setItemText(5, _translate("PlotEditor", "yellow"))
        self.line_color_cb.setItemText(6, _translate("PlotEditor", "purple"))
        self.linewidth_cb.setCurrentText(_translate("PlotEditor", "2"))
        self.linewidth_cb.setItemText(0, _translate("PlotEditor", "0.5"))
        self.linewidth_cb.setItemText(1, _translate("PlotEditor", "1"))
        self.linewidth_cb.setItemText(2, _translate("PlotEditor", "1.5"))
        self.linewidth_cb.setItemText(3, _translate("PlotEditor", "2"))
        self.linewidth_cb.setItemText(4, _translate("PlotEditor", "3"))
        self.linewidth_cb.setItemText(5, _translate("PlotEditor", "4"))
        self.linewidth_cb.setItemText(6, _translate("PlotEditor", "5"))
        self.linewidth_cb.setItemText(7, _translate("PlotEditor", "7.5"))
        self.linewidth_cb.setItemText(8, _translate("PlotEditor", "10"))
        self.linewidth_cb.setItemText(9, _translate("PlotEditor", "15"))
        self.linewidth_cb.setItemText(10, _translate("PlotEditor", "20"))
        self.linestyle_l.setText(_translate("PlotEditor", "Line Style"))
        self.label.setText(_translate("PlotEditor", "Background Color:"))
        self.label_3.setText(_translate("PlotEditor", "Figure"))
        self.background_color_cb.setItemText(0, _translate("PlotEditor", "black"))
        self.background_color_cb.setItemText(1, _translate("PlotEditor", "white"))
        self.background_color_cb.setItemText(2, _translate("PlotEditor", "red"))
        self.background_color_cb.setItemText(3, _translate("PlotEditor", "blue"))
        self.background_color_cb.setItemText(4, _translate("PlotEditor", "green"))
        self.background_color_cb.setItemText(5, _translate("PlotEditor", "yellow"))
        self.background_color_cb.setItemText(6, _translate("PlotEditor", "purple"))
        self.show_plot_bt.setText(_translate("PlotEditor", "Show Plot"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PlotEditor = QtWidgets.QDialog()
    ui = Ui_PlotEditor()
    ui.setupUi(PlotEditor)
    PlotEditor.show()
    sys.exit(app.exec_())

