# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ploteditorgui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PlotEditor(object):
    def setupUi(self, PlotEditor):
        PlotEditor.setObjectName("PlotEditor")
        PlotEditor.resize(1064, 702)
        PlotEditor.setMinimumSize(QtCore.QSize(710, 499))
        self.layoutWidget = QtWidgets.QWidget(PlotEditor)
        self.layoutWidget.setGeometry(QtCore.QRect(270, 620, 314, 63))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.show_plot_bt = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.show_plot_bt.setFont(font)
        self.show_plot_bt.setObjectName("show_plot_bt")
        self.horizontalLayout.addWidget(self.show_plot_bt)
        self.editor_cancel_bt = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.editor_cancel_bt.setFont(font)
        self.editor_cancel_bt.setObjectName("editor_cancel_bt")
        self.horizontalLayout.addWidget(self.editor_cancel_bt)
        self.layoutWidget1 = QtWidgets.QWidget(PlotEditor)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 80, 832, 178))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.layoutWidget1.setFont(font)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.vertical_label_l = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.vertical_label_l.setFont(font)
        self.vertical_label_l.setObjectName("vertical_label_l")
        self.gridLayout.addWidget(self.vertical_label_l, 1, 0, 1, 1)
        self.vertical_label_le = QtWidgets.QLineEdit(self.layoutWidget1)
        self.vertical_label_le.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.vertical_label_le.setFont(font)
        self.vertical_label_le.setText("")
        self.vertical_label_le.setObjectName("vertical_label_le")
        self.gridLayout.addWidget(self.vertical_label_le, 1, 1, 1, 2)
        self.font_sb = QtWidgets.QFontComboBox(self.layoutWidget1)
        self.font_sb.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.font_sb.setFont(font)
        self.font_sb.setObjectName("font_sb")
        self.gridLayout.addWidget(self.font_sb, 2, 2, 1, 1)
        self.font_size_sb = QtWidgets.QComboBox(self.layoutWidget1)
        self.font_size_sb.setEnabled(True)
        self.font_size_sb.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.font_size_sb.setFont(font)
        self.font_size_sb.setEditable(True)
        self.font_size_sb.setMaxVisibleItems(16)
        self.font_size_sb.setMinimumContentsLength(0)
        self.font_size_sb.setObjectName("font_size_sb")
        self.font_size_sb.addItem("")
        self.font_size_sb.addItem("")
        self.font_size_sb.addItem("")
        self.font_size_sb.addItem("")
        self.font_size_sb.addItem("")
        self.font_size_sb.addItem("")
        self.font_size_sb.addItem("")
        self.font_size_sb.addItem("")
        self.font_size_sb.addItem("")
        self.font_size_sb.addItem("")
        self.font_size_sb.addItem("")
        self.font_size_sb.addItem("")
        self.font_size_sb.addItem("")
        self.gridLayout.addWidget(self.font_size_sb, 2, 1, 1, 1)
        self.horizontal_label_le = QtWidgets.QLineEdit(self.layoutWidget1)
        self.horizontal_label_le.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.horizontal_label_le.setFont(font)
        self.horizontal_label_le.setInputMask("")
        self.horizontal_label_le.setText("")
        self.horizontal_label_le.setFrame(True)
        self.horizontal_label_le.setObjectName("horizontal_label_le")
        self.gridLayout.addWidget(self.horizontal_label_le, 0, 1, 1, 2)
        self.horizontal_label_l = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.horizontal_label_l.setFont(font)
        self.horizontal_label_l.setObjectName("horizontal_label_l")
        self.gridLayout.addWidget(self.horizontal_label_l, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.linestyle_l = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.linestyle_l.setFont(font)
        self.linestyle_l.setObjectName("linestyle_l")
        self.gridLayout.addWidget(self.linestyle_l, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 2, 1, 1)
        self.linestyle_cb = QtWidgets.QComboBox(self.layoutWidget1)
        self.linestyle_cb.setObjectName("linestyle_cb")
        self.linestyle_cb.addItem("")
        self.linestyle_cb.addItem("")
        self.linestyle_cb.addItem("")
        self.gridLayout.addWidget(self.linestyle_cb, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(PlotEditor)
        self.label.setGeometry(QtCore.QRect(60, 400, 220, 42))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(PlotEditor)
        self.label_4.setGeometry(QtCore.QRect(30, 550, 220, 69))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(PlotEditor)
        self.label_2.setGeometry(QtCore.QRect(40, 420, 220, 149))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.figure_size_l = QtWidgets.QLabel(PlotEditor)
        self.figure_size_l.setGeometry(QtCore.QRect(80, 320, 200, 33))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.figure_size_l.setFont(font)
        self.figure_size_l.setObjectName("figure_size_l")

        self.retranslateUi(PlotEditor)
        QtCore.QMetaObject.connectSlotsByName(PlotEditor)

    def retranslateUi(self, PlotEditor):
        _translate = QtCore.QCoreApplication.translate
        PlotEditor.setWindowTitle(_translate("PlotEditor", "Plot Editor"))
        self.show_plot_bt.setText(_translate("PlotEditor", "Show Plot"))
        self.editor_cancel_bt.setText(_translate("PlotEditor", "Cancel"))
        self.vertical_label_l.setText(_translate("PlotEditor", "<html><head/><body><p>Vertical Label:</p></body></html>"))
        self.vertical_label_le.setPlaceholderText(_translate("PlotEditor", "y"))
        self.font_size_sb.setItemText(0, _translate("PlotEditor", "8"))
        self.font_size_sb.setItemText(1, _translate("PlotEditor", "9"))
        self.font_size_sb.setItemText(2, _translate("PlotEditor", "10"))
        self.font_size_sb.setItemText(3, _translate("PlotEditor", "11"))
        self.font_size_sb.setItemText(4, _translate("PlotEditor", "12"))
        self.font_size_sb.setItemText(5, _translate("PlotEditor", "14"))
        self.font_size_sb.setItemText(6, _translate("PlotEditor", "16"))
        self.font_size_sb.setItemText(7, _translate("PlotEditor", "18"))
        self.font_size_sb.setItemText(8, _translate("PlotEditor", "20"))
        self.font_size_sb.setItemText(9, _translate("PlotEditor", "22"))
        self.font_size_sb.setItemText(10, _translate("PlotEditor", "24"))
        self.font_size_sb.setItemText(11, _translate("PlotEditor", "26"))
        self.font_size_sb.setItemText(12, _translate("PlotEditor", "28"))
        self.horizontal_label_le.setPlaceholderText(_translate("PlotEditor", "x"))
        self.horizontal_label_l.setText(_translate("PlotEditor", "Horizontal Label: "))
        self.label_3.setText(_translate("PlotEditor", "Font: "))
        self.linestyle_l.setText(_translate("PlotEditor", "Line Style"))
        self.label_6.setText(_translate("PlotEditor", "Color"))
        self.linestyle_cb.setItemText(0, _translate("PlotEditor", "________"))
        self.linestyle_cb.setItemText(1, _translate("PlotEditor", "_ _ _ _ _"))
        self.linestyle_cb.setItemText(2, _translate("PlotEditor", ". . . . . . . "))
        self.label.setText(_translate("PlotEditor", "Axis Color:"))
        self.label_4.setText(_translate("PlotEditor", "Background Color:"))
        self.label_2.setText(_translate("PlotEditor", "Axis Line Width:"))
        self.figure_size_l.setText(_translate("PlotEditor", "<html><head/><body><p><span style=\" font-size:10pt;\">Figure Size:</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PlotEditor = QtWidgets.QDialog()
    ui = Ui_PlotEditor()
    ui.setupUi(PlotEditor)
    PlotEditor.show()
    sys.exit(app.exec_())

