# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ploteditorgui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PlotEditor(object):
    def setupUi(self, PlotEditor):
        PlotEditor.setObjectName("PlotEditor")
        PlotEditor.resize(951, 702)
        PlotEditor.setMinimumSize(QtCore.QSize(710, 499))
        self.layoutWidget = QtWidgets.QWidget(PlotEditor)
        self.layoutWidget.setGeometry(QtCore.QRect(200, 470, 290, 63))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.show_plot_bt = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.show_plot_bt.setFont(font)
        self.show_plot_bt.setObjectName("show_plot_bt")
        self.horizontalLayout.addWidget(self.show_plot_bt)
        self.editor_cancel_bt = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.editor_cancel_bt.setFont(font)
        self.editor_cancel_bt.setObjectName("editor_cancel_bt")
        self.horizontalLayout.addWidget(self.editor_cancel_bt)
        self.layoutWidget1 = QtWidgets.QWidget(PlotEditor)
        self.layoutWidget1.setGeometry(QtCore.QRect(14, 30, 651, 121))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.layoutWidget1.setFont(font)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.vertical_label_le = QtWidgets.QLineEdit(self.layoutWidget1)
        self.vertical_label_le.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.vertical_label_le.setFont(font)
        self.vertical_label_le.setText("")
        self.vertical_label_le.setObjectName("vertical_label_le")
        self.gridLayout.addWidget(self.vertical_label_le, 1, 1, 1, 1)
        self.vertical_label_l = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.vertical_label_l.setFont(font)
        self.vertical_label_l.setObjectName("vertical_label_l")
        self.gridLayout.addWidget(self.vertical_label_l, 1, 0, 1, 1)
        self.font_sice_horizontal_sb = QtWidgets.QComboBox(self.layoutWidget1)
        self.font_sice_horizontal_sb.setEnabled(True)
        self.font_sice_horizontal_sb.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.font_sice_horizontal_sb.setFont(font)
        self.font_sice_horizontal_sb.setEditable(True)
        self.font_sice_horizontal_sb.setMaxVisibleItems(16)
        self.font_sice_horizontal_sb.setMinimumContentsLength(0)
        self.font_sice_horizontal_sb.setObjectName("font_sice_horizontal_sb")
        self.font_sice_horizontal_sb.addItem("")
        self.font_sice_horizontal_sb.addItem("")
        self.font_sice_horizontal_sb.addItem("")
        self.font_sice_horizontal_sb.addItem("")
        self.font_sice_horizontal_sb.addItem("")
        self.font_sice_horizontal_sb.addItem("")
        self.font_sice_horizontal_sb.addItem("")
        self.font_sice_horizontal_sb.addItem("")
        self.font_sice_horizontal_sb.addItem("")
        self.font_sice_horizontal_sb.addItem("")
        self.font_sice_horizontal_sb.addItem("")
        self.font_sice_horizontal_sb.addItem("")
        self.font_sice_horizontal_sb.addItem("")
        self.gridLayout.addWidget(self.font_sice_horizontal_sb, 0, 3, 1, 1)
        self.font_size_vertical_sb = QtWidgets.QComboBox(self.layoutWidget1)
        self.font_size_vertical_sb.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.font_size_vertical_sb.setFont(font)
        self.font_size_vertical_sb.setEditable(True)
        self.font_size_vertical_sb.setMaxVisibleItems(16)
        self.font_size_vertical_sb.setMinimumContentsLength(0)
        self.font_size_vertical_sb.setObjectName("font_size_vertical_sb")
        self.font_size_vertical_sb.addItem("")
        self.font_size_vertical_sb.addItem("")
        self.font_size_vertical_sb.addItem("")
        self.font_size_vertical_sb.addItem("")
        self.font_size_vertical_sb.addItem("")
        self.font_size_vertical_sb.addItem("")
        self.font_size_vertical_sb.addItem("")
        self.font_size_vertical_sb.addItem("")
        self.font_size_vertical_sb.addItem("")
        self.font_size_vertical_sb.addItem("")
        self.font_size_vertical_sb.addItem("")
        self.font_size_vertical_sb.addItem("")
        self.font_size_vertical_sb.addItem("")
        self.gridLayout.addWidget(self.font_size_vertical_sb, 1, 3, 1, 1)
        self.vertical_label_font_sb = QtWidgets.QFontComboBox(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vertical_label_font_sb.sizePolicy().hasHeightForWidth())
        self.vertical_label_font_sb.setSizePolicy(sizePolicy)
        self.vertical_label_font_sb.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.vertical_label_font_sb.setFont(font)
        self.vertical_label_font_sb.setObjectName("vertical_label_font_sb")
        self.gridLayout.addWidget(self.vertical_label_font_sb, 1, 2, 1, 1)
        self.figure_size_sb = QtWidgets.QDoubleSpinBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.figure_size_sb.setFont(font)
        self.figure_size_sb.setObjectName("figure_size_sb")
        self.gridLayout.addWidget(self.figure_size_sb, 2, 1, 1, 1)
        self.figure_size_l = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.figure_size_l.setFont(font)
        self.figure_size_l.setObjectName("figure_size_l")
        self.gridLayout.addWidget(self.figure_size_l, 2, 0, 1, 1)
        self.horizontal_label_le = QtWidgets.QLineEdit(self.layoutWidget1)
        self.horizontal_label_le.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.horizontal_label_le.setFont(font)
        self.horizontal_label_le.setInputMask("")
        self.horizontal_label_le.setText("")
        self.horizontal_label_le.setFrame(True)
        self.horizontal_label_le.setObjectName("horizontal_label_le")
        self.gridLayout.addWidget(self.horizontal_label_le, 0, 1, 1, 1)
        self.horizontal_label_font_sb = QtWidgets.QFontComboBox(self.layoutWidget1)
        self.horizontal_label_font_sb.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.horizontal_label_font_sb.setFont(font)
        self.horizontal_label_font_sb.setObjectName("horizontal_label_font_sb")
        self.gridLayout.addWidget(self.horizontal_label_font_sb, 0, 2, 1, 1)
        self.horizontal_label_l = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.horizontal_label_l.setFont(font)
        self.horizontal_label_l.setScaledContents(False)
        self.horizontal_label_l.setObjectName("horizontal_label_l")
        self.gridLayout.addWidget(self.horizontal_label_l, 0, 0, 1, 1)
        self.widget = QtWidgets.QWidget(PlotEditor)
        self.widget.setGeometry(QtCore.QRect(10, 170, 108, 151))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)

        self.retranslateUi(PlotEditor)
        QtCore.QMetaObject.connectSlotsByName(PlotEditor)

    def retranslateUi(self, PlotEditor):
        _translate = QtCore.QCoreApplication.translate
        PlotEditor.setWindowTitle(_translate("PlotEditor", "Plot Editor"))
        self.show_plot_bt.setText(_translate("PlotEditor", "Show Plot"))
        self.editor_cancel_bt.setText(_translate("PlotEditor", "Cancel"))
        self.vertical_label_le.setPlaceholderText(_translate("PlotEditor", "y"))
        self.vertical_label_l.setText(_translate("PlotEditor", "<html><head/><body><p>Vertical Label:</p></body></html>"))
        self.font_sice_horizontal_sb.setItemText(0, _translate("PlotEditor", "8"))
        self.font_sice_horizontal_sb.setItemText(1, _translate("PlotEditor", "9"))
        self.font_sice_horizontal_sb.setItemText(2, _translate("PlotEditor", "10"))
        self.font_sice_horizontal_sb.setItemText(3, _translate("PlotEditor", "11"))
        self.font_sice_horizontal_sb.setItemText(4, _translate("PlotEditor", "12"))
        self.font_sice_horizontal_sb.setItemText(5, _translate("PlotEditor", "14"))
        self.font_sice_horizontal_sb.setItemText(6, _translate("PlotEditor", "16"))
        self.font_sice_horizontal_sb.setItemText(7, _translate("PlotEditor", "18"))
        self.font_sice_horizontal_sb.setItemText(8, _translate("PlotEditor", "20"))
        self.font_sice_horizontal_sb.setItemText(9, _translate("PlotEditor", "22"))
        self.font_sice_horizontal_sb.setItemText(10, _translate("PlotEditor", "24"))
        self.font_sice_horizontal_sb.setItemText(11, _translate("PlotEditor", "26"))
        self.font_sice_horizontal_sb.setItemText(12, _translate("PlotEditor", "28"))
        self.font_size_vertical_sb.setItemText(0, _translate("PlotEditor", "8"))
        self.font_size_vertical_sb.setItemText(1, _translate("PlotEditor", "9"))
        self.font_size_vertical_sb.setItemText(2, _translate("PlotEditor", "10"))
        self.font_size_vertical_sb.setItemText(3, _translate("PlotEditor", "11"))
        self.font_size_vertical_sb.setItemText(4, _translate("PlotEditor", "12"))
        self.font_size_vertical_sb.setItemText(5, _translate("PlotEditor", "14"))
        self.font_size_vertical_sb.setItemText(6, _translate("PlotEditor", "16"))
        self.font_size_vertical_sb.setItemText(7, _translate("PlotEditor", "18"))
        self.font_size_vertical_sb.setItemText(8, _translate("PlotEditor", "20"))
        self.font_size_vertical_sb.setItemText(9, _translate("PlotEditor", "22"))
        self.font_size_vertical_sb.setItemText(10, _translate("PlotEditor", "24"))
        self.font_size_vertical_sb.setItemText(11, _translate("PlotEditor", "26"))
        self.font_size_vertical_sb.setItemText(12, _translate("PlotEditor", "28"))
        self.figure_size_l.setText(_translate("PlotEditor", "<html><head/><body><p><span style=\" font-size:10pt;\">Figure Size:</span></p></body></html>"))
        self.horizontal_label_le.setPlaceholderText(_translate("PlotEditor", "x"))
        self.horizontal_label_l.setText(_translate("PlotEditor", "<html><head/><body><p><span style=\" font-size:10pt;\">Horizontal Label:</span></p></body></html>"))
        self.label_2.setText(_translate("PlotEditor", "Axis Line Width:"))
        self.label_4.setText(_translate("PlotEditor", "Background Color:"))
        self.label.setText(_translate("PlotEditor", "Axis Color:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PlotEditor = QtWidgets.QDialog()
    ui = Ui_PlotEditor()
    ui.setupUi(PlotEditor)
    PlotEditor.show()
    sys.exit(app.exec_())

